
spring:
  application:
    name: spring-batch-rdbms
  sql:
    init:
      mode: always
  batch:
#    jdbc:
#      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: insight5688

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.batch.item.database: DEBUG